### ISSUE TITLE
unable to invoke 'uptobox-cli' as a command

### ISSUE THREAD

**Issue by theRiggg** [vic-blt/uptobox-cli#4]
I was wondering if you can submit to me the 'how to' install  'uptobox-cli' as a command. even after installing all the dependencies and setuped the config.json file in the uptobox-cli folder you still cant invoke uptobox-cli as a command.

**Comment by vic-blt** [comment]
You can create a CLI alias like this
`alias uptobox="node <PATH_TO_UPTOBOX-CLI>/index.js"`
